import Head from 'next/head'

import TopBar from '../components/header'
import ComingSoon from '../components/comingsoon'
import Main from '../components/Main'

export default function Home() {
  return (
    <div  className='bg-black text-white w-full'>
      <Head>
        <title>Rocktet Monsiter </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div  ><TopBar/>
      </div>
      <div className='flex  justify-center items-center drop-shadow-md hover:drop-shadow-xl'> <ComingSoon/></div>
      <div className='flex justify-center items-baseline  pt-2  pl-1'> <Main/></div>
      <div className='flex justify-center items-center '> <button className='mb-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full'> Connect Wallet</button></div>
      
    </div>
  )
}
